DATA SEGMENT
    NUM DW 5H
    FACT DW 2 DUP<0>
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AX,01H    ;INITIALIZE AX WITH VALUE 01H
    MOV CX,NUM    ;LOAD THE VALUE OF NUM IN COUNT REGISTER CX
    UP: MUL CX    ;START A LOOP WHICH MULTIPLIES CX
    LOOP UP       ;LOOP UNTIL VALUE OF CX IS NOT ZERO
    MOV FACT,AX   ;MOVE THE RESULT TO FACT
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
